import { createContext } from 'react';

export const mainContext = createContext({
    menuOpen: false,
    setMenuOpen: () => {},
    score: 0,
    setScore: () => {},
    correctAnswer: 0,
    setCorrectAnswer: () => {},
    wrongAnswer: 0,
    setWrongAnswer: () => {},
    startTime: 0,
    endTime: 0,
    setEndTime: () => {},
    nowDate: 0,
    showExam: false,
    startExam: () => {},
    setHamIconIsShow: () => {},
    hamIconIsShow: false,
    isShowNav: false,
    setIsShowNav: () => {},
    questions: [],
    setQuestions: () => {},
    isFinishExam: false,
    setIsFinishExam: () => {},
});
